services:
   - docker
language: cpp
os:
  - linux
compiler:
  - gcc
addons:
  apt:
    packages:
      - cmake
      - g++
script:
  - mkdir release
  - cd release
  - cmake .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --target all
  - ./PerfTestCombinedFixedSizeMsg
  - cd .. && rm -r release/
after_success:
  - sh .travis/deploy_dockerhub.sh
