services:
   - docker
language: cpp
os:
  - linux
compiler:
  - gcc
addons:
  apt:
    packages:
      - cmake
      - g++
script:
  - mkdir debug
  - cd debug
  - cmake .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . --target all
  - ./PerfTestCombinedFixedSizeMsg
after_success:
  - cd ..
  - sh .travis/deploy_dockerhub.sh
